name: Codebase basic Access
dcc_uri: dev/config/codebase_basic_access
dcc_definition_type: config
version: "1.6"
schema: v1
description: supply a basic access to the codebase
dcc_tags:
  - frontend
  - web
  - dev
dcc_config_type: agents
models:
  - dcc_use: dev/models/gemini_25_pro
context:
  - dcc_use: dev/context/code
  - dcc_use: dev/context/file
  - dcc_use: dev/context/terminal
  - dcc_use: dev/context/tree
rules: []
prompts: []
docs: []
mcpServers: []
