name: Frontend Code Reviewer
dcc_uri: dev/configs/fe_code_reviewer
dcc_definition_type: config
version: "1.3"
schema: v1
description: Config for agents that do a code review for frontend code
dcc_tags:
  - codereview
  - readonly
  - frontend
dcc_config_type: agents
models:
  - dcc_use: dev/models/gemini_25_flash
context:
  - dcc_use: dev/context/code
  - dcc_use: dev/context/current_file
  - dcc_use: dev/context/file
  - dcc_use: dev/context/open
rules:
  - dcc_use: dev/rules/dev-core-rules
  - dcc_use: dev/rules/frontend_core_rules
prompts: []
docs: []
mcpServers:
  - dcc_use: dev/mcpservers/playwright_mcp
  - dcc_use: dev/mcpservers/browsaer_mcp
