name: UI Worker
dcc_uri: dev/config/ui_worker2
dcc_definition_type: config
version: "1.3"
schema: v1
description: include only src folder
dcc_tags:
  - frontend
  - web
  - dev
dcc_config_type: ide
models:
  - dcc_use: dev/models/gemini_25_flash
rules: []
prompts: []
docs: []
mcpServers: []
